# Generated by Django 5.0.3 on 2024-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_muscles',
            field=models.ManyToManyField(related_name='exercises', to='userR.musclegroup'),
        ),
    ]
