# Generated by Django 5.0.3 on 2024-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userR', '0003_workoutplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='current_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('hero', 'Hero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='workout_goal',
            field=models.CharField(choices=[('cut', 'Cut'), ('bulk', 'Bulk')], max_length=50),
        ),
    ]
