# Generated by Django 5.0.3 on 2024-03-13 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userR', '0005_alter_workoutplan_workout_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='workout_frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3, 'Frequency must be at least 3 day per week'), django.core.validators.MaxValueValidator(7, 'Frequency cannot exceed 7 days per week')]),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='userR.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userR.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_exercises', to='userR.workoutday')),
            ],
        ),
    ]
