# Generated by Django 5.0.3 on 2024-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userR', '0006_alter_workoutplan_workout_frequency_workoutday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayexercise',
            name='reps',
            field=models.CharField(max_length=10),
        ),
    ]
